url: "https://emrekayik.github.io"
baseurl: ""
lang: "tr-TR"

title: "/home/emre"
description: "projelerim, yazılarım ve daha fazlası."
author:
  name: Emre Kayık
  email: emrekayik1905@gmail.com
  twitter: emrekayik0


disqus:
  shortname: emrekayik

collections:
  projects:
    output: true
    permalink: /projeler/:title/
  posts:
    output: true
    permalink: /blog/:title/
  suggestions:
    output: false
    permalink: /suggestions/:title/

defaults:
  - scope:
      path: ""
      type: "projeler"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Emre"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-tailwind
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship


date_locale: tr


jekyll_admin:
  homepage: "posts"
  layout: "admin"
  title: "Admin Panel"
  url: "http://localhost:4000/admin"
  # Add any other plugins you want to use here
  # For example, if you want to use the jekyll-sitemap plugin:


reading_time:
  words_per_minute: 250 # Dakikada 250 kelime olarak ayarla
  minutes_per_image: 0.2 # Her resim için 0.2 dakika (12 saniye) ekle


highlighter: rouge

postcss:
  cache: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .github
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - .vscode
  - .DS_Store
  - .idea
  - .env
  - package.json
  - package-lock.json
  - tailwind.config.js

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/